name: kursdemo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  pod_player: ^0.1.2
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.1.11
  flutter_quill: ^7.1.16+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

 
